<a href="https://colab.research.google.com/github/samreenkauser/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/S7%268.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1 LOAD A CSV

In [ ]:
import pandas as pd

df = pd.read_csv("session6_policy_data.csv")
print("shape:", df.shape)
df.head()

shape: (51, 5)

    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
1    South  2021             88.7            15.2       62000
2     East  2021             91.2             9.8       48000
3     West  2021             85.4            11.1       53000
4  Central  2021             90.1            14.0       59000

1.2 . FIRST LOOK - HEAD,TAIL,INFO,DESCRIBE

In [ ]:
df.head(3)

  region  year  employment_rate  budget_million  population
0  North  2021             92.3            12.5       50000
1  South  2021             88.7            15.2       62000
2   East  2021             91.2             9.8       48000

In [ ]:
df.tail(3)

     region  year  employment_rate  budget_million  population
48     West  2030             91.5            15.5       57500
49  Central  2030             95.5            18.5       63500
50    North  2021             92.3            12.5       50000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           51 non-null     object
 1   year             51 non-null     int64
 2   employment_rate  51 non-null     float64
 3   budget_million   49 non-null     float64
 4   population       51 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB

In [ ]:
df.describe()

              year  employment_rate  budget_million    population
count    51.000000        51.000000       49.000000     51.000000
mean   2025.411765        92.100000       14.646939  56321.078431
std       2.940588         2.646205        2.469826   5943.875782
min    2021.000000        85.400000        9.800000  48000.000000
25%    2023.000000        90.650000       12.600000  51012.500000
50%    2025.000000        92.400000       14.500000  55000.000000
75%    2028.000000        93.950000       16.500000  62000.000000
max    2030.000000        97.000000       19.500000  67400.000000

1.3 . A COLUMN IS A SERIES

In [ ]:
regions = df[["region","employment_rate"]]
print(regions.head())
print(regions.tail())
regions.describe()

    region  employment_rate
0    North             92.3
1    South             88.7
2     East             91.2
3     West             85.4
4  Central             90.1
     region  employment_rate
46    South             94.5
47     East             94.8
48     West             91.5
49  Central             95.5
50    North             92.3

       employment_rate
count        51.000000
mean         92.100000
std           2.646205
min          85.400000
25%          90.650000
50%          92.400000
75%          93.950000
max          97.000000

SECTION 2. SELECTING - COLUMNS,LOC AND ILOC

    . df["col"]- one column(a series).df[["a","b"]] - several column (a dataframe).
    . df.loc[...]selects by label(rowindex/column name)
    . df.iloc[...]selects by position(0- based numbers),exactly like numpy

2.1 . SELECT COLUMNS

In [ ]:
df[["region", "employment_rate"]].head()

    region  employment_rate
0    North             92.3
1    South             88.7
2     East             91.2
3     West             85.4
4  Central             90.1

2.2. loc - by label

In [ ]:
print(df.loc[0])
print(df.loc[0, "employment_rate"])

region             North
year                2021
employment_rate     92.3
budget_million      12.5
population         50000
Name: 0, dtype: object
92.3

2.3 .iloc - by position

In [ ]:
print(df.iloc[0,2])
print(df.iloc[:3,:2])

92.3
  region  year
0  North  2021
1  South  2021
2   East  2021

practice time - selecting
from df,print(1) the populatioon column's first 5 values,and (2) the value at row 4,column budget_million using iloc.

In [ ]:
print(df["population"].head())
print(df.head(10))
print(df.iloc[4,3])

0    50000
1    62000
2    48000
3    53000
4    59000
Name: population, dtype: int64
    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
1    South  2021             88.7            15.2       62000
2     East  2021             91.2             9.8       48000
3     West  2021             85.4            11.1       53000
4  Central  2021             90.1            14.0       59000
5    North  2022             92.8            13.0       50225
6    South  2022             89.3             NaN       62600
7     East  2022             91.6            10.3       48450
8     West  2022             86.1            11.6       53500
9  Central  2022             90.7            14.5       59500
14.0

Section 3 . Filtering Rows

3.1. One Condition

In [ ]:
high = df[df["employment_rate"] > 92]

print(high.shape)
high.head()

(28, 5)

    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
5    North  2022             92.8            13.0       50225
10  north   2023             93.3            13.5       50450
15   North  2024             93.9            14.0       50675
17    East  2024             92.4            11.2       49350

3.2. Two Conditions  -use &(AND)/|(or),each side in()

In [ ]:
recent_high = df[(df["employment_rate"] > 92) & (df["year"] >= 2027)]
recent_high[["region", "year","employment_rate"]].head()

     region  year  employment_rate
30    North  2027             95.4
31    South  2027             92.5
32     East  2027             93.6
34  Central  2027             93.7
35    North  2028             95.9

practice time - filtering

keep only the rows where population is greater than 60000. how many rows is that?

In [ ]:
big = df[df["population"] > 60000]
print(big.shape[0], "rows")
big[["region","year", "population"]].head()

17 rows

     region  year  population
1     South  2021       62000
6     South  2022       62600
11    South  2023       63200
16    South  2024       63800
19  Central  2024       60500

4.1. Missing values

Section 4 . Cleaning - missing values,duplicates & messy text

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           51 non-null     object
 1   year             51 non-null     int64
 2   employment_rate  51 non-null     float64
 3   budget_million   49 non-null     float64
 4   population       51 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB

In [ ]:
df.isna().sum()

region             0
year               0
employment_rate    0
budget_million     2
population         0
dtype: int64

In [ ]:
print(df.isna().sum())

mean_budget = df["budget_million"].mean()

region             0
year               0
employment_rate    0
budget_million     2
population         0
dtype: int64

In [ ]:
df_clean = df.copy()

df_clean["budget_million"] = df_clean["budget_million"].fillna(mean_budget)

print(df_clean["budget_million"].isna().sum())
print(df_clean.info())

0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           51 non-null     object
 1   year             51 non-null     int64
 2   employment_rate  51 non-null     float64
 3   budget_million   51 non-null     float64
 4   population       51 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB
None

4.2 . Duplicate rows

In [ ]:
print("duplicates:", df_clean.duplicated().sum())
df_clean = df_clean.drop_duplicates()
print("after drop:", df_clean.shape)

duplicates: 1
after drop: (50, 5)

4.3. Messy Text - clean the regio labels

In [ ]:
print(df_clean["region"].unique())

df_clean["region"] = df_clean["region"].str.strip().str.title()
print(df_clean["region"].unique())

['North' 'South' 'East' 'West' 'Central' 'north ']
['North' 'South' 'East' 'West' 'Central']

practice time - cleaning

In [ ]:
d = pd.read_csv("session6_policy_data.csv")
d["budget_million"] = d["budget_million"].fillna(d["budget_million"].median())
print("missiing now:", d["budget_million"].isna().sum())
print("duplicates:", d.duplicated().sum())

missiing now: 0
duplicates: 1

Section 5. Groupby & Aggregate

5.1. Average by region

In [ ]:
avg_emp = df_clean.groupby("region")["employment_rate"].mean().sort_values(ascending=False)
print(avg_emp)

region
North      94.64
East       93.00
Central    92.80
South      91.58
West       88.46
Name: employment_rate, dtype: float64

5.2. Several aggregations at once with .agg

In [ ]:
summary = df_clean.groupby("region").agg(
  avg_employment=("employment_rate", "mean"),
  total_population=("population","sum"),
  years=("year","count"),)
summary

         avg_employment  total_population  years
region
Central           92.80            612500     10
East              93.00            500250     10
North             94.64            510125     10
South             91.58            647000     10
West              88.46            552500     10

Section 6 . Merge / Join two tables

In [ ]:
lookup = pd.read_csv("session6_region_lookup.csv")
lookup

    region    zone  target_employment
0    North  Zone-A               93.0
1    South  Zone-B               92.0
2     East  Zone-A               93.5
3     West  Zone-C               90.0
4  Central  Zone-B               93.0

6.1. Left merge on region

In [ ]:
merged = pd.merge(df_clean, lookup, on="region", how="left")
print(merged.shape)
merged[["region","year","employment_rate", "zone","target_employment"]].head()

(50, 7)

    region  year  employment_rate    zone  target_employment
0    North  2021             92.3  Zone-A               93.0
1    South  2021             88.7  Zone-B               92.0
2     East  2021             91.2  Zone-A               93.5
3     West  2021             85.4  Zone-C               90.0
4  Central  2021             90.1  Zone-B               93.0

Practice time - merge

After merging,create a boolean column above_target that is True when employment_rate is at or above target_employment.Then print how many rows are above target.

In [ ]:
merged["above_target"] = merged["employment_rate"] >= merged["target_employment"]
merged
print(merged["above_target"].sum(),"rows at or above target")

24 rows at or above target

Section 7. Bringing it together - A policy analysis

In [ ]:
# 1. load
data = pd.read_csv("session6_policy_data.csv")

#2. clean
data["budget_million"] = data["budget_million"].fillna(data["budget_million"].mean())
data = data.drop_duplicates()
data["region"] = data["region"].str.strip().str.title()

#3. merge in targets
data = pd.merge(data,pd.read_csv("session6_region_lookup.csv"),on="region", how="left")

#4. per-region:average employment vs target
report = data.groupby("region").agg(
    avg_employment=("employment_rate","mean"),
    target=("target_employment", "first"),
).reset_index()
report["meets_target"] = report["avg_employment"] >= report["target"]
report

    region  avg_employment  target  meets_target
0  Central           92.80    93.0         False
1     East           93.00    93.5         False
2    North           94.64    93.0          True
3    South           91.58    92.0         False
4     West           88.46    90.0         False

Section 8. Mini Challenges

Challenge 1. The 2030 snapshot

Filter df_clean to just the year 2030 and sshow region + employment_rate,highest first.

In [ ]:
snap = df_clean[df_clean["year"] == 2030].sort_values("employment_rate", ascending=False)
snap[["region", "employment_rate"]]

     region  employment_rate
45    North             97.0
49  Central             95.5
47     East             94.8
46    South             94.5
48     West             91.5

Challenge 2. Biggest budget region

Which region has the highest total budget across all years?

In [ ]:
totals = df_clean.groupby("region")["budget_million"].sum()
print(totals.idxmax(), "->", round(totals.max(),1))

South -> 172.5

Challenge 3. Growth check

For North,print employment_rate in 2021 and 2030,and the change between them.

In [ ]:
north = df_clean[df_clean["region"] == "North"]
rate_2021 = north[north["year"] == 2021]["employment_rate"].iloc[0]
rate_2030 = north[north["year"] == 2030]["employment_rate"].iloc[0]

change = rate_2030 - rate_2021

print("2021:", rate_2021)
print("2030:", rate_2030)
print("change:", change)

2021: 92.3
2030: 97.0
change: 4.700000000000003